const ExampleRoutes = [
	{
		path: '/examples',
		name: 'Example',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/examples/layout',
		meta: {
			title: '功能示例',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'iconfont icon-xitongshezhi',
		},
		children: [
			{
				path: '/examples/layout',
				name: 'LayoutView',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/examples/layout/layout-basic',
				meta: {
					title: '布局示例',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
				children: [
					{
						path: '/examples/layout/layout-basic',
						name: 'LayoutBasicView',
						meta: {
							title: '布局示例-基础',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('/@/views/examples/container/ContainerView.vue'),
					},
					{
						path: '/examples/layout/layout-page',
						name: 'LayoutPageView',
						meta: {
							title: '布局示例-搜索',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('/@/views/examples/container/BasePageView.vue'),
					},
					{
						path: '/examples/layout/rk-container-top-bottom',
						name: 'RKContainerTopBottomView',
						meta: {
							title: '布局示例-上下',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('/@/views/examples/container/RkTopBottomView.vue'),
					},
					{
						path: '/examples/layout/rk-container',
						name: 'RKContainerView',
						meta: {
							title: '布局示例-完整',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('/@/views/examples/container/RKContainerView.vue'),
					},
				],
			},
			{
				path: '/examples/component',
				name: 'ComponentView',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/examples/component/select-demo',
				meta: {
					title: '组件示例',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
				children: [
					{
						path: '/examples/component/select-demo',
						name: 'TreeSelectView',
						component: () => import('/@/views/examples/component/TreeSelectView.vue'),
						meta: {
							title: '下拉选择',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
					},
					{
						path: '/examples/component/tree-demo',
						name: 'TreeDemoView',
						component: () => import('/@/views/examples/TreeDemoView.vue'),
						meta: {
							title: '树形结构',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
					},
					{
						path: '/examples/component/tree-panel',
						name: 'TreePanelView',
						component: () => import('/@/views/examples/component/TreePanelView.vue'),
						meta: {
							title: '树形面板',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
					},
				],
			},
			{
				path: '/examples/table',
				name: 'TableView',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/examples/table/edit-table',
				meta: {
					title: '表格示例',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
				children: [
					{
						path: '/examples/table/edit-table',
						name: 'EditTableView',
						meta: {
							title: '编辑表格',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('@/views/examples/table/EditTableView.vue'),
					},
					{
						path: '/examples/table/pager-table',
						name: 'PagerTableView',
						meta: {
							title: '分页表格',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('@/views/examples/table/PagerTableView.vue'),
					},
					{
						path: '/examples/table/checkbox-table',
						name: 'CheckboxTableView',
						meta: {
							title: '复选框表格',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caidan',
						},
						component: () => import('@/views/examples/table/CheckboxTableView.vue'),
					},
				],
			},
		],
	},
];

export default ExampleRoutes;
